name: Prettier Code Formatter

on:
  push:
    branches:
      - dev

jobs:
  prettier:
    name: Run Prettier on Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier Check
        run: npm run format-check
